name: analysis
channels:
    - conda-forge
    - pytorch
dependencies:
    - uproot
    - h5py
    - keras
    - tensorflow
    - scikit-learn
    - scikit-optimize
    - matplotlib
    - pandas
    - pytorch
    - jupyter